[build]
  publish = "build"
  command = "NODE_OPTIONS=--openssl-legacy-provider react-scripts build"

[build.environment]
  NODE_VERSION = "18.20.5"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
